fujaba/fulib.org

src/main/angular/src/app/config-modal/config-modal.component.html
* Form fields in the Project Configuration window are now properly validated. #47 
Closes #47
=> Implement form validation for config modal

src/main/angular/src/app/assignment/my-assignments/my-assignments.component.html, src/main/angular/src/app/assignment/task-list/task-list.component.html, src/main/angular/src/app/footer/footer.component.html
* Improved the accessibility for some links in the footer.
* Made the "Show Output" and "Grade" links in task lists actual buttons.
=> Improve link accessibility

src/main/angular/src/app/assignment/assignment-info/assignment-info.component.html, src/main/angular/src/app/assignment/assignment.service.ts, src/main/angular/src/app/assignment/course.service.ts, src/main/angular/src/app/assignment/course/course.component.ts, src/main/angular/src/app/assignment/create-assignment/create-assignment.component.html, src/main/angular/src/app/assignment/create-assignment/create-assignment.component.ts, src/main/angular/src/app/assignment/create-course/create-course.component.ts, src/main/angular/src/app/assignment/create-solution/create-solution.component.html, src/main/angular/src/app/assignment/create-solution/create-solution.component.ts, src/main/angular/src/app/assignment/grade-form/grade-form.component.ts, src/main/angular/src/app/assignment/import-export/import-export.component.ts, src/main/angular/src/app/assignment/model/assignment.ts, src/main/angular/src/app/assignment/my-solutions/my-solutions.component.html, src/main/angular/src/app/assignment/my-solutions/my-solutions.component.ts, src/main/angular/src/app/assignment/solution-table/solution-table.component.html, src/main/angular/src/app/assignment/solution-table/solution-table.component.ts, src/main/angular/src/app/assignment/solution.service.ts, src/main/angular/src/app/assignment/solution/solution.component.ts, src/main/angular/src/app/assignment/task-list/task-list.component.ts, src/main/angular/src/app/changelog.service.ts, src/main/angular/src/app/changelog/changelog.component.ts, src/main/angular/src/app/config-modal/config-modal.component.ts, src/main/angular/src/app/examples.service.ts, src/main/angular/src/app/four-pane-editor/four-pane-editor.component.ts, src/main/angular/src/app/model/codegen/request.ts, src/main/angular/src/app/privacy.service.ts, src/main/angular/src/app/storage.service.ts, src/main/angular/src/polyfills.ts, src/main/angular/tsconfig.json
This enables the TypeScript `strictNullChecks` option and resolves all resulting errors, potentially avoiding some problems.
=> Enable strict null checks

build.gradle, src/main/resources/org/fulib/webapp/projectzip/build.gradle
* Downloaded `build.gradle` files no longer dictate Java version compatibility.
=> Minor improvements in build.gradle

src/main/angular/src/app/app.component.html, src/main/angular/src/app/app.module.ts, src/main/angular/src/app/footer/footer.component.scss, src/main/angular/src/app/header/header.component.html, src/main/angular/src/app/header/header.component.ts, src/main/angular/src/app/privacy/privacy.component.html, src/main/angular/src/styles.scss
* Changed the footer into a header.
=> Site header instead of footer

LICENSE.md, README.md, build.gradle, src/main/angular/src/app/about/about.component.html, src/main/angular/src/app/about/about.component.scss, src/main/angular/src/app/about/about.component.ts, src/main/angular/src/app/app-routing.module.ts, src/main/angular/src/app/app.module.ts, src/main/angular/src/app/header/header.component.html, src/main/angular/src/app/modal/modal.component.ts
+ Added a License.
+ Added the About page under Legal in the header for viewing third-party licenses.
=> About page with licenses

build.gradle, src/main/java/org/fulib/webapp/tool/MarkdownUtil.java, src/test/java/org/fulib/webapp/tool/MarkdownUtilTest.java
* Updated to fulibYaml v1.4.0.
* Updated to fulibTables v1.4.0.
+ Added support for task lists when rendering Markdown.
=> Update dependencies and render task lists in Markdown

src/main/angular/src/app/feedback/feedback.component.html, src/main/angular/src/app/feedback/feedback.component.ts, src/main/angular/src/app/header/header.component.html, src/main/angular/src/app/privacy/privacy.component.html, src/main/angular/src/styles.scss
* Restructured the navigation bar and added a link for Getting Started.
* Added a Close button to the Feedback modal.
* Removed the contact email from the Feedback modal.
=> Improve navigation bar and feedback

src/main/angular/package.json, src/main/angular/pnpm-lock.yaml, src/main/angular/src/app/app.component.html, src/main/angular/src/app/app.module.ts, src/main/angular/src/app/changelog.service.ts, src/main/angular/src/app/four-pane-editor/four-pane-editor.component.html, src/main/angular/src/app/four-pane-editor/four-pane-editor.component.scss, src/main/angular/src/app/four-pane-editor/four-pane-editor.component.ts, src/main/angular/src/app/markdown.service.ts, src/main/angular/src/app/scenario-editor.service.ts, src/main/angular/src/styles.scss
+ Panels in the main editor can now be rearranged and hidden. #109
+ Added the Markdown panel to the main editor. #110
+ Added the Output panel to the main editor. #111
Closes #109, #110, #111
=> Configurable Editor Panels

src/main/angular/src/app/assignment/assignment-info/assignment-info.component.html, src/main/angular/src/app/assignment/course/course.component.html, src/main/angular/src/app/assignment/solution/solution.component.html, src/main/angular/src/app/changelog/changelog.component.html, src/main/angular/src/app/four-pane-editor/four-pane-editor.component.html, src/main/angular/src/styles.scss, src/main/java/org/fulib/webapp/tool/MarkdownUtil.java, src/test/java/org/fulib/webapp/tool/MarkdownUtilTest.java
* Blockquotes, fenced code blocks and tables are now properly rendered and styled in Markdown views.
=> Improved Markdown rendering

src/main/angular/src/app/four-pane-editor/four-pane-editor.component.html, src/main/angular/src/app/pipes/exception.pipe.ts, src/main/angular/src/app/shared/shared.module.ts
+ The output panel now detects exceptions and displays a link for reporting them.
=> Detect exceptions in output and display issue creation link

src/main/angular/src/app/assignment/assignment.service.ts, src/main/angular/src/app/four-pane-editor/four-pane-editor.component.html, src/main/angular/src/app/four-pane-editor/four-pane-editor.component.ts, src/main/angular/src/app/model/codegen/diagram.ts, src/main/angular/src/app/model/codegen/response.ts, src/main/angular/src/app/pipes/safe-resource-url.pipe.ts, src/main/angular/src/app/pipes/safe-url.pipe.ts, src/main/angular/src/app/shared/shared.module.ts, src/main/java/org/fulib/webapp/WebService.java, src/main/java/org/fulib/webapp/assignment/Assignments.java, src/main/java/org/fulib/webapp/assignment/Comments.java, src/main/java/org/fulib/webapp/assignment/Courses.java, src/main/java/org/fulib/webapp/assignment/Solutions.java, src/main/java/org/fulib/webapp/tool/MarkdownUtil.java, src/main/java/org/fulib/webapp/tool/RunCodeGen.java, src/main/java/org/fulib/webapp/tool/model/Diagram.java, src/main/java/org/fulib/webapp/tool/model/Result.java, src/test/java/org/fulib/webapp/WebServiceTest.java, src/test/java/org/fulib/webapp/assignment/AssignmentsTest.java, src/test/java/org/fulib/webapp/assignment/CommentsTest.java, src/test/java/org/fulib/webapp/assignment/CoursesTest.java, src/test/java/org/fulib/webapp/assignment/SolutionsTest.java, src/test/java/org/fulib/webapp/tool/MarkdownUtilTest.java
+ Diagrams and files generated as part of scenario compilation are now available as URLs for up to an hour.
This allows the Markdown panel to correctly display diagrams and improved behaviour of HTML mockups.
=> Make diagrams and project files available

src/main/angular/src/app/assignment/solution-table/solution-table.component.html, src/main/angular/src/app/assignment/solution-table/solution-table.component.ts
* The View button in the solutions table now correctly links to the solution again.
=> Fix View button in solutions table

build.gradle, src/main/angular/src/app/changelog.service.ts, src/main/angular/src/app/changelog/changelog.component.ts, src/main/angular/src/app/header/header.component.ts, src/main/angular/src/environments/environment.gradle.ts, src/main/angular/src/environments/environment.prod.ts, src/main/angular/src/environments/environment.ts, src/main/java/org/fulib/webapp/WebService.java, src/main/java/org/fulib/webapp/mongo/Mongo.java, src/main/resources/org/fulib/webapp/version.properties, src/test/java/org/fulib/webapp/WebServiceTest.java
+ Added the `GET /api/versions` endpoint for retrieving the versions of different fulib components.
=> Add GET /api/versions endpoint

frontend/src/app/four-pane-editor/four-pane-editor.component.html, frontend/src/app/four-pane-editor/four-pane-editor.component.ts
+ Added the View menu for showing and hiding editor panels and removed the bottom bar.
+ Added the Reset Editor Layout button in the View menu.
=> Editor View Menu

build.gradle, frontend/src/assets/examples/definitions/Placeholders.md
* Updated to fulibScenarios v1.6.2.
* Updated to fulibTools v1.4.1.
* Expanded the Placeholders example with inheritance and more objects.
=> fulibScenarios v1.6.2

build.gradle, src/main/java/org/fulib/webapp/WebService.java, src/main/java/org/fulib/webapp/tool/RunCodeGen.java
Enables output of SLF4J log messages and replaces a few uses of java.util.logging with the SLF4J API.
=> Logging with SLF4J

frontend/src/app/app.module.ts, frontend/src/app/diagram-view/diagram-view.component.html, frontend/src/app/diagram-view/diagram-view.component.ts, frontend/src/app/four-pane-editor/four-pane-editor.component.html, frontend/src/app/four-pane-editor/four-pane-editor.component.ts, frontend/src/app/shared/preview/preview.component.html, frontend/src/app/shared/preview/preview.component.ts, frontend/src/app/shared/shared.module.ts
+ Class and object diagrams can now be viewed in full screen by clicking.
* Increased the size of class and object diagrams.
Closes #125
=> Click to enlarge diagrams

frontend/src/app/app.module.ts, frontend/src/app/header/header.component.html, frontend/src/app/header/header.component.ts, frontend/src/environments/environment.prod.ts, frontend/src/environments/environment.ts
* Edit Account under the user icon now opens in a new tab.
* Fixed incorrect auth settings in backend leading to unverified assignments.
* Fixed incorrect Edit Account URL under the user icon.
=> Fix auth URLs

frontend/src/app/app.module.ts
* Fixed Changelogs failing to load when logged in.
=> Fix Changelog failing to load when logged in

frontend/src/app/shared/autotheme-codemirror/autotheme-codemirror.component.ts, frontend/src/app/shared/lint.service.ts, frontend/src/app/shared/scenario-codemirror/scenario-codemirror.component.html, frontend/src/app/shared/scenario-codemirror/scenario-codemirror.component.ts, frontend/src/main.ts, frontend/src/styles.scss, frontend/src/styles/codemirror/hint.scss, frontend/src/styles/codemirror/lint.scss
+ Added basic autocompletion for previous words in scenario editors. #148
* Slightly improved editor tooltip style.
* Editor tooltips now display above the navigation bar so they are always readable, even if long.
Closes #148
=> Editor Autocompletion

frontend/src/app/assignment/assignment-routing.module.ts, frontend/src/app/assignment/assignment.module.ts, frontend/src/app/assignment/components/edit-task-list/edit-task-list.component.html, frontend/src/app/assignment/components/edit-task-list/edit-task-list.component.ts, frontend/src/app/assignment/pages/edit-assignment/classroom/classroom.component.html, frontend/src/app/assignment/pages/edit-assignment/classroom/classroom.component.spec.ts, frontend/src/app/assignment/pages/edit-assignment/classroom/classroom.component.ts, frontend/src/app/assignment/pages/edit-assignment/edit-assignment.component.html, frontend/src/app/assignment/pages/edit-assignment/edit-assignment.component.ts, frontend/src/app/assignment/pages/edit-assignment/info/info.component.html, frontend/src/app/assignment/pages/edit-assignment/info/info.component.spec.ts, frontend/src/app/assignment/pages/edit-assignment/info/info.component.ts, frontend/src/app/assignment/pages/edit-assignment/preview/preview.component.html, frontend/src/app/assignment/pages/edit-assignment/preview/preview.component.spec.ts, frontend/src/app/assignment/pages/edit-assignment/preview/preview.component.ts, frontend/src/app/assignment/pages/edit-assignment/sample/sample.component.html, frontend/src/app/assignment/pages/edit-assignment/sample/sample.component.spec.ts, frontend/src/app/assignment/pages/edit-assignment/sample/sample.component.ts, frontend/src/app/assignment/pages/edit-assignment/tasks/tasks.component.html, frontend/src/app/assignment/pages/edit-assignment/tasks/tasks.component.spec.ts, frontend/src/app/assignment/pages/edit-assignment/tasks/tasks.component.ts, frontend/src/app/assignment/pages/edit-assignment/template/template.component.html, frontend/src/app/assignment/pages/edit-assignment/template/template.component.spec.ts, frontend/src/app/assignment/pages/edit-assignment/template/template.component.ts, frontend/src/app/assignment/pages/edit-task-modal/edit-task-modal.component.html, frontend/src/app/assignment/pages/edit-task-modal/edit-task-modal.component.ts, frontend/src/app/assignment/services/assignment.context.ts
* Editing/Creating Assignments is now separated into multiple steps.
=> Edit Assignment in Steps

frontend/src/app/assignment/pages/solution/solution.component.html, frontend/src/app/assignment/pages/solution/solution.component.ts
* The Solution view is now organized in tabs.
=> Organize Solution View in Tabs

frontend/src/app/assignment/components/comment-list/comment-list.component.html, frontend/src/app/assignment/components/comment-list/comment-list.component.ts, frontend/src/app/assignment/pages/assignment/assignment.component.html, frontend/src/app/assignment/pages/assignment/assignment.component.ts, frontend/src/app/assignment/pages/create-course/create-course.component.ts, frontend/src/app/assignment/pages/create-solution/create-solution.component.ts, frontend/src/app/assignment/pages/edit-assignment/preview/preview.component.ts, frontend/src/app/assignment/pages/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/pages/solution-table/solution-table.component.ts, frontend/src/app/header/header.component.html, frontend/src/app/header/header.component.ts, frontend/src/app/toast.service.spec.ts, frontend/src/app/toast.service.ts
+ Added success and error toasts for various assignment-related actions.
=> Error Toasts

frontend/src/app/assignment/pages/evaluation-modal/evaluation-modal.component.html, frontend/src/app/assignment/pages/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/pages/solution/solution.component.ts, frontend/src/app/assignment/services/solution.service.ts, frontend/src/app/assignment/services/task.service.ts, frontend/src/app/shared/pro-tip/pro-tip.component.html, frontend/src/app/shared/pro-tip/pro-tip.component.spec.ts, frontend/src/app/shared/pro-tip/pro-tip.component.ts, frontend/src/app/shared/shared.module.ts
+ Added keyboard shortcuts for the Evaluation modal.
+ Added buttons for min/max points in Evaluation form.
+ Added button to delete an Evaluation.
* The solution task list is now updated after adding an evaluation.
* Improved the Evaluation preview.
=> Improve Evaluations

frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/app/editor/config/config.component.html, frontend/src/app/editor/config/config.component.ts, frontend/src/app/header/header.component.html, frontend/src/app/home/home.component.html, frontend/src/app/home/home.component.spec.ts, frontend/src/app/home/home.component.ts
=> Add Home page

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/app/app.module.ts, frontend/src/app/assignment/assignment.module.ts, frontend/src/app/assignment/pages/assignment-statistics/assignment-statistics.component.html, frontend/src/app/assignment/pages/assignment-statistics/assignment-statistics.component.spec.ts, frontend/src/app/assignment/pages/assignment-statistics/assignment-statistics.component.ts, frontend/src/app/assignment/pages/assignment/assignment.component.html, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/evaluation/evaluation.controller.ts
+ Added statistics for most given evaluations.
=> Evaluation Statistics

frontend/src/app/assignment/modules/solution/details/details.component.html, frontend/src/app/assignment/modules/solution/details/details.component.ts, frontend/src/app/assignment/services/solution.service.ts
+ A solution's student info can now be edited.
=> Edit student info

frontend/src/app/assignment/model/evaluation.ts, frontend/src/app/assignment/modules/assignment/assignment-routing.module.ts, frontend/src/app/assignment/modules/assignment/assignment.module.ts, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, frontend/src/app/assignment/modules/assignment/submit-modal/submit-modal.component.html, frontend/src/app/assignment/modules/assignment/submit-modal/submit-modal.component.spec.ts, frontend/src/app/assignment/modules/assignment/submit-modal/submit-modal.component.ts, frontend/src/app/assignment/modules/assignment/submit.service.spec.ts, frontend/src/app/assignment/modules/assignment/submit.service.ts, frontend/src/app/assignment/services/solution.service.ts, frontend/src/app/assignment/services/task.service.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/assignment/assignment.service.ts, services/apps/assignments/src/classroom/classroom.controller.ts, services/apps/assignments/src/classroom/classroom.service.ts
+ Added a modal to submit feedback via Email, GitHub Issue Draft or GitHub Issue API.
* Tasks may now have an empty description for "Other"-type remarks.
=> Modal to Submit Feedback

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/assignment/search/search.component.html, frontend/src/app/assignment/modules/assignment/search/search.component.ts, frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.html, frontend/src/app/assignment/modules/shared/task-list/task-list.component.html, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/classroom/classroom.service.ts, services/apps/assignments/src/evaluation/evaluation.dto.ts, services/apps/assignments/src/evaluation/evaluation.service.ts, services/apps/assignments/src/search/search.controller.ts, services/apps/assignments/src/search/search.dto.ts, services/apps/assignments/src/search/search.service.ts
+ Made Code Search optional with a switch in assignment Classroom settings.
+ Code Search for Evaluations can now be configured in fulibFeedback.
+ The Task List now shows the Evaluation Author.
=> Code Search Improvements

frontend/src/app/projects/modules/editor/file-code-editor/file-code-editor.component.ts, services/apps/projects/src/member/member.controller.ts
* The Code Editor no longer wants to confirm external changes if the content matches.
* Project Member lists are now properly filtered by project.
=> Projects Fixes

gradle/wrapper/gradle-wrapper.properties, projects/Dockerfile
* Updated to Gradle v7.3 for Java 17 support.
=> Update to Gradle v7.3

frontend/src/app/assignment/modules/assignment/assignment.module.ts, frontend/src/app/assignment/modules/assignment/statistic-value/statistic-value.component.html, frontend/src/app/assignment/modules/assignment/statistic-value/statistic-value.component.spec.ts, frontend/src/app/assignment/modules/assignment/statistic-value/statistic-value.component.ts, frontend/src/app/assignment/modules/assignment/statistics.service.ts, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.html, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.ts, services/apps/assignments/src/assignments.module.ts, services/apps/assignments/src/evaluation/evaluation.service.ts, services/apps/assignments/src/statistics/statistics.controller.spec.ts, services/apps/assignments/src/statistics/statistics.controller.ts, services/apps/assignments/src/statistics/statistics.dto.ts, services/apps/assignments/src/statistics/statistics.module.ts, services/apps/assignments/src/statistics/statistics.service.spec.ts, services/apps/assignments/src/statistics/statistics.service.ts
+ Added overview statistics for Solutions and Evaluations.
* Statistics are now calculated in the backend service.
=> Improved Statistics

frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.html, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/evaluation/evaluation.controller.ts
+ Added an info box about the original for Code Search-derived evaluations.
* Improved the layout of the Evaluation modal.
=> Improve Evaluation Modal

frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.html, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/modules/solution/selection.service.spec.ts, frontend/src/app/assignment/modules/solution/selection.service.ts, frontend/src/app/assignment/modules/solution/tasks/tasks.component.ts, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/assignment/assignment-auth.guard.ts, services/apps/assignments/src/assignments.module.ts, services/apps/assignments/src/evaluation/evaluation.controller.ts, services/apps/assignments/src/evaluation/evaluation.service.ts, services/apps/assignments/src/selection/selection.controller.spec.ts, services/apps/assignments/src/selection/selection.controller.ts, services/apps/assignments/src/selection/selection.dto.ts, services/apps/assignments/src/selection/selection.module.ts, services/apps/assignments/src/selection/selection.service.spec.ts, services/apps/assignments/src/selection/selection.service.ts, services/apps/assignments/src/solution/solution-auth.guard.ts
Instead of selecting the task in fulibFeedback via Code Action, we just send the selection to the frontend via the backend service and let the user set points and comments via the web interface.
=> Synchronized fulibFeedback Selection

frontend/src/app/assignment/model/solution.ts, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/statistics.service.ts, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.html, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.scss, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.ts, frontend/src/app/assignment/modules/assignment/submit-modal/submit-modal.component.html, frontend/src/app/assignment/modules/assignment/submit-modal/submit-modal.component.ts, frontend/src/app/assignment/modules/assignment/submit.service.ts, frontend/src/app/assignment/services/task.service.ts, services/apps/assignments/src/solution/solution.dto.ts, services/apps/assignments/src/solution/solution.schema.ts, services/apps/assignments/src/solution/solution.service.ts, services/apps/assignments/src/statistics/statistics.dto.ts, services/apps/assignments/src/statistics/statistics.service.ts
+ Graded solutions now store the total of points after submitting feedback.
=> Graded Solution Points

frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/assignee/assignee.module.ts, services/apps/assignments/src/solution/solution.controller.ts, services/apps/assignments/src/solution/solution.module.ts
* Solution search now happens in the backend.
* The Solution search bar now displays the number of results.
=> Search Solutions on Backend Service

frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.html, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/modules/solution/solution.module.ts
+ Added Autocompletion / Typeahead for Evaluation Remarks and Snippet Comments (selected from other evaluations for the same task).
=> Evaluation Typeahead

frontend/src/app/assignment/modules/assignment/assignment.module.ts, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts
Added options for selecting which IDE and method (https/ssh) to use when cloning repositories.
Thanks @nataschu
=> Clone Options for IDE and HTTPS/SSH

frontend/src/app/app-routing.module.ts, frontend/src/app/app.component.ts, frontend/src/app/assignment/assignment-routing.module.ts, frontend/src/app/assignment/modules/assignment/assignment-routing.module.ts, frontend/src/app/assignment/modules/edit-assignment/edit-assignment-routing.module.ts, frontend/src/app/assignment/modules/solution/solution-routing.module.ts, frontend/src/app/docs/docs-routing.module.ts, frontend/src/app/docs/page/page.component.ts, frontend/src/app/editor/editor-routing.module.ts, frontend/src/app/projects/modules/launch/launch-routing.module.ts, frontend/src/app/projects/modules/project-panel/project-panel-routing.module.ts, frontend/src/app/projects/modules/settings/settings-routing.module.ts, frontend/src/app/projects/modules/setup/setup-routing.module.ts, frontend/src/app/projects/projects-routing.module.ts, services/apps/projects/src/environment.ts
+ The page / tab title is now updated automatically.
=> Page Titles

frontend/src/app/assignment/modules/assignment/share/share.component.html, frontend/src/app/assignment/modules/assignment/share/share.component.ts, frontend/src/app/assignment/modules/solution/share/share.component.html, frontend/src/app/assignment/modules/solution/share/share.component.ts, frontend/src/main.ts
+ The Share Assignment/Solution pages now include JSON settings for fulibFeedback.
=> Show fulibFeedback settings in Sharing views

frontend/src/app/about/about.component.html, frontend/src/app/changelog/changelog.component.html, frontend/src/app/feedback/feedback.component.html, frontend/src/app/privacy/privacy.component.html, frontend/src/app/privacy/privacy.component.ts
* Improved the style and semantics of the Changelog, About, Feedback and Privacy modal buttons.
=> Improve Modals

backend/src/main/java/org/fulib/webapp/tool/Tools.java, frontend/src/assets/examples/prototyping/UIs.md
- Removed support for the `.html.png` diagram format.
=> Remove .html.png diagram format

frontend/src/app/assignment/modules/assignment/submit-modal/submit-modal.component.html, frontend/src/app/assignment/modules/assignment/submit-modal/submit-modal.component.ts
* Submit Feedback as Mail is now always possible.
* Added Copy Markdown and Copy HTML buttons.
=> More Submit Feedback Options

frontend/src/app/assignment/modules/solution/comment-list/comment-list.component.html, frontend/src/app/assignment/modules/solution/comment-list/comment-list.component.ts, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/comment/comment.controller.ts, services/apps/assignments/src/comment/comment.service.ts
+ Added live updating of comments. #80
Closes #80
=> Comment Events

frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/evaluation/evaluation.controller.ts, services/apps/assignments/src/evaluation/evaluation.service.ts
+ Solutions that are (partially) evaluated are now highlighted in the table.
Also improved performance of the evaluation modal by only loading required data for remark and snippet comment completion. In addition, the number of elements in the solution table was slightly removed for increased performance with many solutions.
=> Highlight Evaluated Solutions in Table

frontend/src/app/assignment/modules/assignment/assignment.module.ts, frontend/src/app/assignment/modules/assignment/statistics.service.ts, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.html, services/apps/assignments/src/statistics/statistics.dto.ts, services/apps/assignments/src/statistics/statistics.service.ts
Improved task statistics to be more meaningful and explain the numbers.
=> Improved Task Statistics

frontend/src/app/assignment/model/telemetry.ts, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, frontend/src/app/assignment/modules/assignment/submit-modal/submit-modal.component.ts, frontend/src/app/assignment/modules/shared/task-list/task-list.component.html, frontend/src/app/assignment/modules/shared/task-list/task-list.component.ts, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/services/telemetry.service.ts, services/apps/assignments/src/assignments.module.ts, services/apps/assignments/src/evaluation/evaluation.module.ts, services/apps/assignments/src/solution/solution.module.ts, services/apps/assignments/src/telemetry/telemetry.controller.spec.ts, services/apps/assignments/src/telemetry/telemetry.controller.ts, services/apps/assignments/src/telemetry/telemetry.dto.ts, services/apps/assignments/src/telemetry/telemetry.module.ts, services/apps/assignments/src/telemetry/telemetry.schema.ts, services/apps/assignments/src/telemetry/telemetry.service.spec.ts, services/apps/assignments/src/telemetry/telemetry.service.ts
+ Added telemetry for time tracking assignment grading.
=> Telemetry for Time Tracking

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.html, frontend/src/app/assignment/modules/edit-assignment/info/info.component.html, frontend/src/app/assignment/modules/edit-assignment/info/info.component.ts, services/apps/assignments/src/assignment/assignment.schema.ts
* Improved the wording in the assignment info form.
Also removed the Classroom link and cleaned up the Classroom form.
=> Minor Improvements to Assignment Editing

frontend/src/app/assignment/modules/assignment/statistics.service.ts, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.html, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.scss, frontend/src/app/shared/duration.pipe.spec.ts, frontend/src/app/shared/duration.pipe.ts, frontend/src/app/shared/shared.module.ts, services/apps/assignments/src/statistics/statistics.dto.ts, services/apps/assignments/src/statistics/statistics.module.ts, services/apps/assignments/src/statistics/statistics.service.ts
+ Added time tracking statistics.
=> Time Tracking Statistics based on Telemetry Data

LICENSE.md
I've updated the year inside the LICENSE.md to 2022.
=> Update year in LICENSE.md

frontend/src/app/assignment/modules/assignment/search/search.component.html, frontend/src/app/assignment/modules/assignment/search/search.component.ts, frontend/src/app/assignment/modules/shared/snippet/snippet.component.html, frontend/src/app/assignment/modules/shared/snippet/snippet.component.ts, frontend/src/app/assignment/modules/solution/selection.service.ts, services/apps/assignments/src/selection/selection.controller.ts
+ The Search page can now be synchronised with the fulibFeedback selection.
=> Synchronise Code Search with Selection

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/assignment/assignment/assignment.component.ts, frontend/src/app/assignment/modules/assignment/share/share.component.html, frontend/src/app/assignment/modules/assignment/share/share.component.ts, frontend/src/app/assignment/modules/assignment/submit.service.ts, frontend/src/app/assignment/modules/edit-assignment/edit-assignment/edit-assignment.component.ts, frontend/src/app/assignment/modules/edit-assignment/preview/preview.component.ts, frontend/src/app/assignment/pages/create-course/create-course.component.ts, frontend/src/app/assignment/pages/create-solution/create-solution.component.ts, frontend/src/app/assignment/pages/my-solutions/my-solutions.component.html, frontend/src/app/assignment/pages/my-solutions/my-solutions.component.ts, frontend/src/app/assignment/services/assignment.service.ts, services/apps/assignments/src/assignment/assignment.dto.ts, services/apps/assignments/src/assignment/assignment.service.ts
+ Added a way to re-generate an assignment token in case it was compromised.
=> Regenerate Assignment Token

frontend/src/app/assignment/modules/assignment/statistics.service.ts, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.html, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.ts, frontend/src/app/shared/duration.pipe.ts, frontend/src/app/shared/shared.module.ts
+ Task Statistics can now be sorted by different measurements.
+ Task Statistics may now display a selectable set of interesting measurements in the header.
=> Statistics Display and Sorting Options

frontend/src/app/assignment/model/search-result.ts, frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.html, frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.spec.ts, frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.ts, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.html, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/modules/solution/solution.module.ts, frontend/src/app/assignment/services/assignment.service.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/evaluation/evaluation.service.ts, services/apps/assignments/src/main.ts, services/apps/assignments/src/search/search.controller.ts, services/apps/assignments/src/search/search.dto.ts, services/apps/assignments/src/search/search.service.ts, services/apps/assignments/src/telemetry/telemetry.schema.ts
+ Changing the fulibFeedback selection in the evaluation modal now displays a Code Search summary including the number of hits, files and solutions, allowing a rough estimate whether the selection provides enough context.
=> Code Search Summary

backend/build.gradle, backend/src/main/resources/org/fulib/webapp/version.properties, frontend/src/app/changelog.service.ts, frontend/src/app/feedback/feedback.component.html
+ Added fulibWorkflows with it's version for feedback modal
+ Added fulibWorkflows with it's version for github list
+ Added fulibWorkflows with it's version for What's new modal
=> Completion of fulibWorkflows integration

frontend/src/app/assignment/modules/edit-assignment/preview/preview.component.html, frontend/src/app/assignment/modules/edit-assignment/preview/preview.component.ts, frontend/src/app/assignment/modules/edit-assignment/task-markdown.service.ts
* The task list markdown editor now handles tasks with positive points without children correctly.
* Deleted tasks are no longer shown in the Preview tab.
=> Bugfixes for Task Lists

frontend/src/app/assignment/assignment-routing.module.ts, frontend/src/app/assignment/assignment.module.ts, frontend/src/app/assignment/pages/my-assignments/my-assignments.component.html, frontend/src/app/assignment/pages/my-courses/my-courses.component.html, frontend/src/app/assignment/pages/my-solutions/my-solutions.component.html, frontend/src/app/assignment/pages/overview/overview.component.html, frontend/src/app/assignment/pages/overview/overview.component.spec.ts, frontend/src/app/assignment/pages/overview/overview.component.ts, frontend/src/app/components/header/header.component.html
* My Assignments, My Courses and My Solutions are now shown on the same page.
=> Show assignments, courses and solutions in overview

frontend/src/app/assignment/modules/shared/task-list/task-list.component.html, frontend/src/app/assignment/modules/shared/task-list/task-list.component.scss, frontend/src/app/assignment/modules/shared/task-list/task-list.component.ts, frontend/src/app/assignment/modules/solution/tasks/tasks.component.ts
* Improved the Solution Task List:
* Unevaluated tasks are now shown in white.
* Added a checkbox for quickly giving 0 or the maximum possible points.
* A simple icon opens the Evaluation modal and indicates whether a user or Code Search created the evaluation.
=> Improved Task List

frontend/src/app/assignment/assignment-routing.module.ts, frontend/src/app/assignment/assignment.module.ts, frontend/src/app/assignment/modules/assignment/search/search.component.ts, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, frontend/src/app/assignment/modules/solution/comment-list/comment-list.component.ts, frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.ts, frontend/src/app/assignment/modules/solution/solution/solution.component.html, frontend/src/app/assignment/pages/my-courses/my-courses.component.html, frontend/src/app/assignment/pages/my-solutions/my-solutions.component.html, frontend/src/app/assignment/pages/overview/overview.component.html, frontend/src/app/assignment/pages/settings/settings.component.html, frontend/src/app/assignment/pages/settings/settings.component.spec.ts, frontend/src/app/assignment/pages/settings/settings.component.ts, frontend/src/app/assignment/services/config.service.ts, frontend/src/app/assignment/services/solution.service.ts
+ Added a global Settings page for Assignments.
=> Global Assignments Settings

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/assignment/assignment/assignment.component.html, frontend/src/app/assignment/modules/shared/assignment-actions/assignment-actions.component.html, frontend/src/app/assignment/modules/shared/assignment-actions/assignment-actions.component.spec.ts, frontend/src/app/assignment/modules/shared/assignment-actions/assignment-actions.component.ts, frontend/src/app/assignment/modules/shared/shared.module.ts, frontend/src/app/assignment/pages/my-assignments/my-assignments.component.html, frontend/src/app/assignment/pages/my-assignments/my-assignments.component.ts, frontend/src/app/assignment/services/assignment.service.ts, services/apps/assignments/src/assignment/assignment.controller.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/assignment/assignment.service.ts
+ Assignments can now be archived.
* Unified actions for assignments into a single reusable dropdown menu.
=> Archive Assignments

frontend/src/app/projects/components/project-list/project-list.component.html
* Improved style of project action buttons.
=> Improve Project Action Buttons

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/pages/create-course/create-course.component.ts, frontend/src/app/assignment/pages/my-assignments/my-assignments.component.ts, frontend/src/app/assignment/pages/my-solutions/my-solutions.component.ts, frontend/src/app/assignment/services/assignment.service.ts, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/assignment/assignment.controller.ts
Improved the way assignments are fetched from the backend service.
Also added a new query parameter for getting all assignments per IDs.
=> Improve Assignments Fetch

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.html, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/classroom/classroom.scheduler.ts
+ Automatic imports of solutions when an assignment deadline has passed can now be notified using a webhook.
=> Notify about imported Solutions on deadline with Webhook

frontend/src/app/assignment/modules/edit-assignment/edit-assignment/edit-assignment.component.html, frontend/src/app/assignment/modules/edit-assignment/edit-assignment/edit-assignment.component.ts, frontend/src/app/assignment/modules/edit-assignment/preview/preview.component.html, frontend/src/app/assignment/modules/edit-assignment/preview/preview.component.ts, frontend/src/app/assignment/services/assignment.service.ts
+ Added an option to delete an assignment draft.
=> Delete Assignment Draft

frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.scss, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts
+ Added copy buttons for columns in solution table.
=> Copy Columns in Solution Table

frontend/src/app/projects/components/project-workspace/project-workspace.component.ts, frontend/src/assets/projects/code-server-images.json, projects/base/Dockerfile, projects/build-all.mjs, projects/generic/Dockerfile, projects/gradle/Dockerfile, projects/nodejs/Dockerfile, services/apps/projects/src/container/container.service.ts, services/apps/projects/src/project/project.schema.ts
Amending #254 to improve the available Docker images. Most importantly, all images (except plain code-server) now include VNC.
=> Improved Project Docker Images

frontend/src/app/assignment/modules/assignment/share/share.component.html, frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.html, frontend/src/app/assignment/modules/shared/author-name/author-name.component.html, frontend/src/app/assignment/modules/solution/share/share.component.html, frontend/src/app/shared/shared.module.ts, frontend/src/app/shared/token-input/token-input.component.html, frontend/src/app/shared/token-input/token-input.component.spec.ts, frontend/src/app/shared/token-input/token-input.component.ts, frontend/src/styles.scss, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/assignment/assignment.service.ts
* Tokens in assignments and solutions are now hidden/blurred by default.
* Classroom tokens are no longer displayed as unset when editing an assignment.
=> Hide Tokens

frontend/src/app/assignment/modules/assignment/submit-modal/submit-modal.component.ts, frontend/src/app/assignment/modules/assignment/submit.service.ts, frontend/src/app/assignment/modules/edit-assignment/tasks/tasks.component.html, frontend/src/app/assignment/modules/solution/event-list/event-list.component.html, frontend/src/app/assignment/modules/solution/event-list/event-list.component.spec.ts, frontend/src/app/assignment/modules/solution/event-list/event-list.component.ts, frontend/src/app/assignment/modules/solution/solution-routing.module.ts, frontend/src/app/assignment/modules/solution/solution.module.ts, frontend/src/app/assignment/modules/solution/solution/solution.component.html, frontend/src/app/assignment/modules/solution/solution/solution.component.ts, frontend/src/app/assignment/services/github.service.spec.ts, frontend/src/app/assignment/services/github.service.ts, frontend/src/app/user/user.service.ts, services/apps/assignments/src/classroom/classroom.service.ts
+ The solution page now includes a view for push events.
* Improved the markdown task editor layout. Thanks @nataschu (https://github.com/fujaba/fulib.org/issues/286#issuecomment-1299887180)
=> Push Events and new Task Markdown Editor

frontend/src/app/assignment/modules/shared/task-list/task-list.component.html, frontend/src/app/assignment/modules/shared/task-list/task-list.component.ts, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/services/solution.service.ts, frontend/src/app/projects/components/project-workspace/project-workspace.component.scss, frontend/src/styles/codemirror/lint.scss, frontend/src/styles/highlight.scss, services/apps/assignments/src/evaluation/evaluation.schema.ts, services/apps/assignments/src/evaluation/evaluation.service.ts
* Evaluations now require an author.
* Evaluations can no longer accidentally exist twice for the same assignment/solution/task.
* Task lists now highlight evaluations with remarks, which is now visible in the tooltip.
=> Fix Evaluation consistency

frontend/src/app/assignment/model/course.ts, frontend/src/app/assignment/modules/course/course-routing.module.ts, frontend/src/app/assignment/modules/course/create-course/create-course.component.html, frontend/src/app/assignment/modules/course/create-course/create-course.component.ts, frontend/src/app/assignment/modules/course/my-courses/my-courses.component.html, frontend/src/app/assignment/modules/course/students/students.component.scss, frontend/src/app/assignment/services/course.service.ts
=> Edit Course

frontend/src/app/projects/components/project-form/project-form.component.html, frontend/src/app/projects/components/project-form/project-form.component.ts, frontend/src/app/projects/components/project-list/project-list.component.html, frontend/src/app/projects/model/project.ts, services/apps/projects/src/project/project.schema.ts
+ Projects can now have a custom icon.
=> Project Icons

frontend/src/app/assignment/model/evaluation.ts, frontend/src/app/assignment/model/task.ts, frontend/src/app/assignment/modules/edit-assignment/edit-task-modal/edit-task-modal.component.html, frontend/src/app/assignment/modules/edit-assignment/info/info.component.ts, frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.html, frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.ts, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.html, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/services/solution.service.ts, frontend/src/app/shared/pro-tip/pro-tip.component.html, services/apps/assignments/src/assignment/assignment.dto.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/evaluation/evaluation.controller.ts, services/apps/assignments/src/evaluation/evaluation.dto.ts, services/apps/assignments/src/evaluation/evaluation.schema.ts, services/apps/assignments/src/evaluation/evaluation.service.ts
+ Added an evaluation note for tasks.
+ Remark suggestions are now displayed immediately and with score and points.
* The task editor modal now allows negative points.
* Restructured the evaluation modal.
* The task editor now saves the verification scenario.
=> Remark Suggestions and Evaluation Note

frontend/src/app/projects/components/project-workspace/project-workspace.component.html, projects/build-all.mjs, projects/gradle/Dockerfile, projects/gradle/build.gradle, services/apps/projects/src/container/container.controller.ts, services/apps/projects/src/container/container.service.ts, services/apps/projects/src/environment.ts, services/apps/projects/src/project/project.service.ts
* Each user uses their own Project container now.
* Users with linked GitHub accounts are now automatically logged into Git in Projects.
* Projects now allow clipboard.
* Fixed some persistence issues with extensions in Projects.
* Improved Gradle Project image performance.
=> Projects Improvements and Fixes

frontend/src/app/projects/components/edit-modal/edit-modal.component.html, frontend/src/app/projects/components/edit-modal/edit-modal.component.ts, frontend/src/app/projects/components/project-form/project-form.component.html, frontend/src/app/projects/components/project-workspace/project-workspace.component.html, frontend/src/app/projects/components/project-workspace/project-workspace.component.ts, projects/images.json, services/apps/projects/src/container/container.service.ts
* Added error handling and better modal behavior when creating/editing projects.
* Added a description for Project Docker Images.
* Simplified the container loading screen and token toast.
=> More Projects Improvements

frontend/src/app/projects/components/project-form/project-form.component.html, frontend/src/app/projects/model/project.ts, services/apps/projects/src/container/container.controller.ts, services/apps/projects/src/container/container.dto.ts, services/apps/projects/src/container/container.service.ts, services/apps/projects/src/project/project.dto.ts, services/apps/projects/src/project/project.schema.ts, services/apps/projects/src/project/project.service.ts
* Projects may specify a starting Git repository that will be pulled on the first launch.
=> Project starting Git Repository

frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.html, frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.ts, frontend/src/app/assignment/modules/edit-assignment/edit-assignment/edit-assignment.component.ts, frontend/src/app/assignment/modules/shared/task-list/task-list.component.ts, frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.html, frontend/src/app/assignment/services/assignment.service.ts, services/apps/assignments/src/classroom/classroom.scheduler.ts, services/apps/assignments/src/classroom/classroom.service.ts
+ Added a Classroom Import pre-check that tries to count the number of solutions 12 hours before the deadline and notifies the Webhook if configured.
* Classroom Import errors are now announced to the Webhook if set.
* Improved the remark suggestion tooltip.
* The checkboxes for quick evaluation now show a toast if an error occurs.
* Importing or exporting an assignment now removes some unwanted properties.
=> Assignment QoL Improvements

services/apps/projects/src/container/container.service.ts
* Fixed a problem where containers would not load correctly when already running.
=> Correctly Find Container

frontend/src/app/assignment/modules/assignment/submit.service.ts
* Improved feedback rendering:
* Improved decision when a task should be shown at all.
* Headlines are used only if the task has children independent of positive or negative points.
* Subtasks are not rendered if an evaluation exists.
=> Improve feedback rendering

frontend/src/app/assignment/modules/shared/pipes/clone-link.pipe.ts, services/apps/assignments/src/classroom/classroom.service.ts, services/apps/projects/src/container/container.service.ts
* Classroom Import now automatically tags the imported commit for easier IDE cloning.
=> Tag on Import

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/edit-assignment/info/info.component.html, frontend/src/app/assignment/modules/edit-assignment/info/info.component.ts, frontend/src/app/assignment/modules/shared/assignment-info/assignment-info.component.html, services/apps/assignments/src/assignment/assignment.schema.ts
+ Assignments may now configure an Issuance date.
* Improved the submission timestamp view in the solution table.
=> Assignment Issuance

README.md
This pull request includes small adjustments to the readme file, including fixed links and badges.
* Fixed link to fulib.org
* Added mention about the other fulib apps
* Fixed non-working badges
=> Small readme adjustments

services/apps/projects/src/container/container.service.ts
* Containers now have access to User ID, username and full name.
* Fixed an error when launching a project with an account that is not connected to GitHub.
=> Minor Container fixes

.github/workflows/deploy.yml, projects/base/Dockerfile, projects/images.json, projects/latex/Dockerfile
* Improved the LaTeX projects image.
=> Improved LaTeX Projects Image

frontend/src/app/assignment/modules/course/course-routing.module.ts, frontend/src/app/assignment/modules/course/create-course/create-course.component.html, frontend/src/app/assignment/modules/course/create-course/create-course.component.ts, frontend/src/app/assignment/modules/course/my-courses/my-courses.component.html, frontend/src/app/assignment/modules/course/students/students.component.html, frontend/src/app/assignment/modules/course/students/students.component.ts, frontend/src/app/assignment/services/course.service.ts, services/apps/assignments/src/course/course.service.ts
+ Edit Course is now a new tab.
+ Added Delete button for courses.
* Column names in the course students overview are now derived from the assignment names.
* Added a loading indicator while the course students overview is generated.
* My Courses now shows the number of assignments in each course.
* Courses now properly merge identical students with multiple author fields.
=> Improved Courses

frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, services/apps/assignments/src/solution/solution.controller.ts, services/apps/assignments/src/solution/solution.dto.ts, services/apps/assignments/src/solution/solution.service.ts
* Bulk solution update now supports matching by ID.
* Bulk solution updates now triggers events.
=> Improve Bulk Solution Update

frontend/src/app/assignment/model/solution.ts, frontend/src/app/assignment/pages/create-solution/create-solution.component.html, frontend/src/app/assignment/pages/create-solution/create-solution.component.ts, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/assignments.module.ts, services/apps/assignments/src/classroom/classroom.module.ts, services/apps/assignments/src/classroom/classroom.service.ts, services/apps/assignments/src/file/file.module.ts, services/apps/assignments/src/file/file.service.ts, services/apps/assignments/src/solution/solution.controller.ts, services/apps/assignments/src/solution/solution.module.ts, services/apps/assignments/src/solution/solution.schema.ts
+ Students may now upload files when submitting their solution.
=> Upload Solution Files

frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.html, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/services/config.service.ts
+ Added config options for enabling Code Search, Snippet Suggestions and Similar Solutions.
=> Toggle Code Search, Snippet Suggestions and Similar Solutions in Config

frontend/pnpm-lock.yaml, frontend/src/app/assignment/model/course.ts, frontend/src/app/assignment/model/solution.ts, frontend/src/app/assignment/modules/assignment/submit.service.ts, frontend/src/app/assignment/modules/course/students/students.component.html, frontend/src/app/assignment/modules/solution/feedback/feedback.component.html, frontend/src/app/assignment/modules/solution/feedback/feedback.component.ts, frontend/src/app/assignment/modules/solution/solution-routing.module.ts, frontend/src/app/assignment/modules/solution/solution.module.ts, services/apps/assignments/src/course/course.dto.ts, services/apps/assignments/src/course/course.service.ts, services/apps/assignments/src/solution/solution.dto.ts, services/apps/assignments/src/solution/solution.schema.ts
+ Added ability for students to submit feedback for a survey.
+ Courses show the number of complete feedbacks submitted by a student.
=> Student Feedback

frontend/src/app/assignment/modules/course/create-course-solutions/create-course-solutions.component.ts, frontend/src/app/assignment/modules/course/create-course/create-course.component.ts, frontend/src/app/assignment/modules/course/students/students.component.html, frontend/src/app/assignment/modules/course/students/students.component.ts, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/modules/solution/similar-modal/similar-modal.component.html, frontend/src/app/assignment/modules/solution/similar-modal/similar-modal.component.ts, frontend/src/app/assignment/modules/solution/tasks/tasks.component.html, frontend/src/app/assignment/services/assignment.service.ts
* Quick Assign buttons in the course students table now have a tooltip with the full name.
* Added some info messages to Similar Solutions when none can be shown.
* The Clone button in a solution no longer triggers a dialog with unsaved changes.
* Course assignments now have the correct order.
* The Similar Solutions modal is no longer shown when the feature is disabled or otherwise not useful.
=> Assignment Fixes

services/apps/assignments/src/assignment/assignment.service.ts, services/apps/assignments/src/comment/comment.service.ts, services/apps/assignments/src/course-member/course-auth.guard.ts, services/apps/assignments/src/course/course.controller.ts, services/apps/assignments/src/course/course.service.ts, services/apps/assignments/src/solution/solution.service.ts, services/apps/assignments/src/utils.ts
* Assignments are now sorted with respect to numbers (e.g. `Assignment 2` sorts before `Assignment 10`).
* Course students now only show results for assignments that the user has access to (is a member).
=> Assignments Bugfixes

frontend/src/app/assignment/model/assignee.ts, frontend/src/app/assignment/model/solution.ts, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, frontend/src/app/assignment/modules/course/students/students.component.html, frontend/src/app/assignment/modules/course/students/students.component.ts, frontend/src/app/assignment/modules/import/import-consent/import-consent.component.html, frontend/src/app/assignment/modules/import/import-consent/import-consent.component.ts, frontend/src/app/assignment/modules/shared/assignee-dropdown/assignee-dropdown.component.html, frontend/src/app/assignment/modules/shared/assignee-dropdown/assignee-dropdown.component.ts, frontend/src/app/assignment/modules/shared/pipes/assignee-color.pipe.ts, frontend/src/app/assignment/services/assignee.service.ts, services/apps/assignments/src/assignee/assignee.controller.ts, services/apps/assignments/src/assignee/assignee.dto.ts
+ Added a way to copy assignees from one assignment to another via a course.
+ Added a button to copy the assignee column in an assignment.
+ Added a button to copy the timestamp column in an assignment.
* Added a confirmation dialog before deleting an assignee.
* Improved visuals of the consent import infobox.
* Consent import no longer allows spaces as separators.
* Consent import now allows inputting tabs.
* Improved assignee colors.
=> Copy Assignees

frontend/src/app/assignment/model/course.ts, frontend/src/app/assignment/modules/course/assignees/assignees.component.html, frontend/src/app/assignment/modules/course/assignees/assignees.component.ts, frontend/src/app/assignment/modules/course/course-routing.module.ts, frontend/src/app/assignment/modules/course/course.module.ts, frontend/src/app/assignment/modules/course/students/students.component.ts, frontend/src/app/assignment/services/course.service.ts, services/apps/assignments/src/assignee/assignee.service.ts, services/apps/assignments/src/course/course.controller.ts, services/apps/assignments/src/course/course.dto.ts, services/apps/assignments/src/course/course.service.ts
+ Added a new Assignees overview page for courses.
=> Course Assignee Overview

frontend/pnpm-lock.yaml, frontend/src/app/assignment/model/solution.ts, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, frontend/src/app/assignment/services/assignee.service.ts, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/assignee/assignee.controller.ts, services/apps/assignments/src/classroom/classroom.service.ts, services/apps/assignments/src/embedding/embedding.controller.ts, services/apps/assignments/src/solution/solution.controller.ts, services/apps/assignments/src/solution/solution.dto.ts, services/apps/assignments/src/solution/solution.service.ts, services/apps/assignments/src/statistics/statistics.service.ts, services/apps/assignments/src/utils.ts
+ Added a solution filter for `status` (graded, started, code-search or todo).
* Improved performance of solution search.
=> Solution Status Filter

services/apps/assignments/src/assignee/assignee.controller.ts, services/apps/assignments/src/assignee/assignee.handler.ts, services/apps/assignments/src/assignee/assignee.schema.ts, services/apps/assignments/src/assignee/assignee.service.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/assignment/assignment.service.ts, services/apps/assignments/src/classroom/classroom.service.ts, services/apps/assignments/src/comment/comment.schema.ts, services/apps/assignments/src/course/course.dto.ts, services/apps/assignments/src/course/course.schema.ts, services/apps/assignments/src/course/course.service.ts, services/apps/assignments/src/evaluation/evaluation.controller.ts, services/apps/assignments/src/evaluation/evaluation.handler.ts, services/apps/assignments/src/evaluation/evaluation.schema.ts, services/apps/assignments/src/evaluation/evaluation.service.ts, services/apps/assignments/src/solution/solution.schema.ts, services/apps/assignments/src/solution/solution.service.ts, services/apps/assignments/src/statistics/statistics.service.ts
* Improved performance of some large tables.
This was mainly done by changing assignment and solution columns in evaluations and assignees to ObjectId, in order to allow better join/$lookup query plans.
=> Fix Aggregation Performance

frontend/src/app/assignment/model/evaluation.ts, frontend/src/app/assignment/modules/course/create-course/create-course.component.ts, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/modules/solution/similar-modal/similar-modal.component.html, frontend/src/app/assignment/modules/solution/similar-modal/similar-modal.component.ts, frontend/src/app/assignment/modules/solution/tasks/tasks.component.ts, frontend/src/app/assignment/services/assignment.service.ts, frontend/src/app/assignment/services/solution.service.ts, services/apps/assignments/src/assignment/assignment.controller.ts, services/apps/assignments/src/evaluation/evaluation.schema.ts, services/apps/assignments/src/solution/solution.controller.ts, services/apps/assignments/src/solution/solution.service.ts
* Evaluations created via Similar Solutions now remember their origin and duration.
* Snippet suggestions now remember their score.
* Improved performance for some fetch operations.
* Improved solution status and origin search.
=> Fixes for Evaluation from Similar Solutions

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/course/students/students.component.html, frontend/src/app/assignment/modules/course/students/students.component.ts, frontend/src/app/assignment/modules/edit-assignment/tasks/tasks.component.html, frontend/src/app/assignment/modules/edit-assignment/tasks/tasks.component.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/statistics/statistics.service.ts
+ Added an option to configure the minimum points required for passing an assignment.
=> Assignment Passing Points

frontend/src/app/assignment/modules/assignment/tasks/tasks.component.html, frontend/src/app/assignment/modules/edit-assignment/preview/preview.component.html, frontend/src/app/assignment/modules/shared/task-list/task-list.component.html, frontend/src/app/assignment/modules/shared/task-list/task-list.component.ts, frontend/src/app/assignment/modules/solution/tasks/tasks.component.html, frontend/src/app/assignment/modules/solution/tasks/tasks.component.ts, frontend/src/app/assignment/pages/create-solution/create-solution.component.html, frontend/src/app/assignment/services/task.service.ts
* Quick Evaluation using checkboxes now updates points more reliably.
=> fix(frontend): Update points on Quick Evaluation without SSE

services/apps/projects/src/container/container.handler.ts, services/apps/projects/src/container/container.module.ts, services/apps/projects/src/container/container.service.ts, services/apps/projects/src/environment.ts, services/apps/projects/src/member/member.handler.ts, services/apps/projects/src/project/project.controller.ts, services/apps/projects/src/project/project.service.ts, services/apps/projects/src/projects.module.ts
=> Fix Project Creation

frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts
+ Added a way to quickly filter the solution table by assignee or status.
+ Added a way to set an assignee for all selected solutions.
=> Quick solution search and assignee

frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, frontend/src/app/assignment/modules/course/students/students.component.html
* Made the course students table header sticky.
=> Sticky Course Students table

frontend/src/app/docs/page-navigation/page-navigation.component.html, frontend/src/app/docs/page-navigation/page-navigation.component.scss
* Improved the side navigation style in Docs.
=> Improve docs nav style

frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.html, frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.ts, services/apps/assignments/src/solution/solution.controller.ts, services/apps/assignments/src/solution/solution.service.ts
* Added a way to find solutions where a task is evaluated with a given remark.
=> Filter solutions by remark

frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts
* Bulk submitting issues for multiple solutions now marks them as graded.
=> Mark solutions as graded after bulk submit

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/edit-assignment/code-search/code-search.component.html, frontend/src/app/assignment/modules/edit-assignment/code-search/code-search.component.ts, frontend/src/app/assignment/modules/import/import-embeddings/import-embeddings.component.html, frontend/src/app/assignment/modules/import/import-embeddings/import-embeddings.component.ts, frontend/src/app/assignment/modules/import/import-modal/import-modal.component.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/embedding/embedding.handler.ts, services/apps/assignments/src/embedding/embedding.service.ts, services/apps/assignments/src/embedding/openai.service.ts, services/package.json, services/pnpm-lock.yaml
+ Added a selection for the OpenAI Embedding Model in the Code Search edit tab.
* OpenAI Embedding imports are now rate limited. The user will see a warning message before importing many functions.
* Embedding import costs are now rounded.
* Adjusted the cost calculation for the (default) `text-embedding-ada-002` model.
=> OpenAI Model Selection

frontend/src/app/assignment/model/assignee.ts, frontend/src/app/assignment/model/solution.ts, frontend/src/app/assignment/modules/assignment/submit.service.ts, frontend/src/app/assignment/modules/shared/task-list/task-list.component.html, frontend/src/app/assignment/modules/shared/task-list/task-list.component.scss, frontend/src/app/assignment/modules/solution/assignee-feedback/assignee-feedback.component.html, frontend/src/app/assignment/modules/solution/feedback/feedback.component.html, frontend/src/app/assignment/modules/solution/tasks/tasks.component.html
* The solution task list now always shows checkboxes.
* When the task list is not editable, they are disabled.
* The color now matches the text and badge.
* The assignee feedback modal no longer appears automatically.
* Added a Cancel button to the assignee feedback modal.
* Improved the issue template:
* Removed the bonus points notice.
* Added a link to the solution.
* The fulib.org link now points to the current instance.
* Feedback forms are now in English.
* Removed the solution feedback banner regarding bonus points.
=> Clean up Feedback after Study

frontend/src/app/shared/markdown-editor/markdown-editor.component.html, frontend/src/app/shared/markdown-editor/markdown-editor.component.ts
+ Added more formatting options to the markdown editor.
=> New Markdown Editor Features

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/edit-assignment/code-search/code-search.component.html, frontend/src/app/assignment/modules/edit-assignment/code-search/code-search.component.ts, frontend/src/app/assignment/modules/edit-assignment/plagiarism-detection/plagiarism-detection.component.html, frontend/src/app/assignment/modules/edit-assignment/plagiarism-detection/plagiarism-detection.component.ts, frontend/src/app/assignment/modules/shared/assignment-info/assignment-info.component.html, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, services/apps/assignments/src/assignment/assignment.dto.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/assignment/assignment.service.ts, services/apps/assignments/src/classroom/classroom.service.ts, services/apps/assignments/src/embedding/embedding.handler.ts, services/apps/assignments/src/embedding/embedding.service.ts, services/apps/assignments/src/moss/moss.service.ts
Moved the OpenAI and Moss config properties to new subdocuments within Assignment.
=> Restructure Assignment OpenAI and Moss Config

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.html, frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/classroom/classroom.service.ts
+ Added an option to specify extra search options in the Classroom settings. This allows including forks, excluding archived repos, etc.
=> Extra search option for GitHub Classroom

services/libs/moss/src/moss-api.ts
* Improved error handling during Moss import.
=> Moss Error Handling
