src/main/angular/src/app/changelog/changelog.component.html
Instead of vertical pills, What's New now arranges the different repos as tabs. This gives the content more space, especially on mobile.
* What's New now arranges repos as tabs. #88
Closes #88
=> Use tabs for What's New

src/main/angular/src/app/assignment/assignment.service.ts, src/main/angular/src/app/assignment/course/course.component.ts, src/main/angular/src/app/assignment/create-course/create-course.component.ts, src/main/angular/src/app/assignment/create-solution/create-solution.component.ts, src/main/angular/src/app/assignment/solution-table/solution-table.component.ts, src/main/angular/src/app/assignment/solution/solution.component.ts
Improves many component implementations to use more idiomatic RxJS, namely avoid nesting `subscribe` calls and using `switchMap` and `forkJoin` where possible.
It was initially planned to introduce `unsubscribe` calls, but that was found to be [unnecessary](https://stackoverflow.com/questions/41138081/do-i-have-to-unsubscribe-from-activatedroute-e-g-params-observables).
* The query parameter `atok` can now be used to set the assignment token when viewing all solutions.
* The query parameters `atok` and `stok` can be now be used to set the assignment or solution token when viewing a solution.
=> Allow settings tokens via URL query parameters and fix unidiomatic use of RxJS

src/main/angular/src/app/four-pane-editor/four-pane-editor.component.ts, src/main/angular/src/app/scenario-editor.service.ts
Selecting no example now correctly displays the stored scenario again. This was broken by 8fba606240bf77c7f161e18f7766b1840c446d83 - since PrivacyService now uses StorageService, values are stored in a cache which needs to be updated.
In addition, selecting an example no longer triggers submit twice.
=> Fix example selection

frontend/src/app/four-pane-editor/four-pane-editor.component.html
* Class and object diagrams can now be scrolled if they are too large for the panel.
=> Scrolling in Class and Object Diagrams

frontend/src/app/four-pane-editor/four-pane-editor.component.ts, frontend/src/app/scenario-editor.service.ts
* The selected example is no longed saved in local storage.
This prevents a weird behaviour where the editor would show an example scenario despite no example being selected.
=> Don't save selected example in localStorage

src/main/java/org/fulib/webapp/WebService.java
Ensures the temporary directory used by runcodegen is always available by creating it if necessary. This prevents a bug where generated files would not be available.
=> Create temp dir for runcodegen

frontend/angular.json, frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/app/header/header.component.html, frontend/src/app/privacy/privacy.component.html
Use bootstrap-icons instead of primer icons. Also updated to ng-bootstrap v9.0.2.
=> Bootstrap Icons

backend/src/main/java/org/fulib/webapp/tool/RunCodeGen.java
* Fixed a problem where the editor would not update the output and other areas when a scenario failed to compile.
=> Render markdown even if scenario compiler fails

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/pages/edit-assignment/edit-assignment.component.ts, frontend/src/app/assignment/pages/edit-assignment/tasks/tasks.component.html, frontend/src/app/assignment/pages/edit-assignment/tasks/tasks.component.ts, frontend/src/app/assignment/services/assignment.service.ts, frontend/src/app/assignment/services/task.service.ts, frontend/src/main.ts, frontend/src/modes/task-list-codemirror-mode.ts
+ Added syntax highlighting when editing tasks as Markdown.
+ Added a syntax guide for editing tasks as Markdown.
+ Added saved drafts when editing existing assignments.
* Tasks with `#` are now ignored in the Markdown editor.
* Task IDs are now parsed correctly.
* Changed to tasks as Markdown are now applied when switching away from the Tasks tab.
Closes #
=> Improved Assignment Editing

frontend/src/app/assignment/modules/assignment/submit.service.ts, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.html, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts
The Evaluation Remark field can now be expanded to a text area. Multiline remarks are displayed correctly in rendered feedback markdown.
Suggested by @nataschu
=> Multiline Evaluation Remarks

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.html, frontend/src/app/assignment/modules/edit-assignment/classroom/classroom.component.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/classroom/classroom.controller.ts, services/apps/assignments/src/classroom/classroom.scheduler.ts, services/apps/assignments/src/classroom/classroom.service.ts, services/apps/assignments/src/environment.ts
This makes it possible for other organisations to use the scheduled import feature.
Manual import no longer requires being logged in or an account linked to GitHub.
The token is automatically redacted from all requests to not leak personal access from the creator to TAs.
=> Specify GitHub token in Classroom settings per assignment

frontend/src/modes/task-list-codemirror-mode.ts
* The pattern for tasks in the Markdown editor now accepts decimal numbers.
=> Relax task markdown pattern

services/apps/assignments/src/assignment/assignment.service.ts
* Editing an assignment no longer deletes the GitHub Classroom token unexpectedly.
=> Don't delete GitHub token when editing Assignment

frontend/src/app/components/privacy/privacy.component.html, frontend/src/app/workflows/download-es/download-es.component.ts
**Please not that this PR has not been tested very well due to the complex workspace setup. Please test before merging!**
If you disable local storage in the privacy settings, create a workflow using [fulibWorkflows](https://fulib.org/workflows) and try to download any type of output, it prints out an error into the little toast in the upper right corner. The error says: "Download Files - Editor Content does not exist". It doesn't matter what types of outputs are selected.
While this is not an error/a bug, the message displayed suggests that something went wrong and the content doesn't exist. Instead something like "Could not download files - Please allow the use of local data storage in your Privacy Preferences." should be displayed.
* Added a note to the Privacy Settings drop down menu. …
=> Make error message for workflow downloads more precise

services/apps/projects/src/container/container.controller.ts, services/apps/projects/src/member/member-auth.guard.ts, services/apps/projects/src/member/member.controller.ts, services/apps/projects/src/member/member.module.ts, services/apps/projects/src/member/member.schema.ts, services/apps/projects/src/member/member.service.ts, services/apps/projects/src/project/project-auth.guard.ts, services/apps/projects/src/project/project.controller.ts, services/apps/projects/src/project/project.module.ts, services/apps/projects/src/project/project.schema.ts, services/apps/projects/src/project/project.service.ts, services/package.json, services/pnpm-lock.yaml
This is just a minor refactor that uses ObjectIds instead of strings in the Projects Service and Members database.
All existing Member documents will be migrated automatically.
=> Use Refs in Project Schemas

services/apps/assignments/src/assignee/assignee.controller.ts, services/apps/assignments/src/assignee/assignee.handler.ts, services/apps/assignments/src/assignee/assignee.service.ts, services/apps/assignments/src/assignment/assignment-auth.guard.ts, services/apps/assignments/src/assignment/assignment.controller.ts, services/apps/assignments/src/assignment/assignment.service.ts, services/apps/assignments/src/classroom/classroom.controller.ts, services/apps/assignments/src/classroom/classroom.service.ts, services/apps/assignments/src/comment/comment-auth.guard.ts, services/apps/assignments/src/comment/comment.controller.ts, services/apps/assignments/src/comment/comment.handler.ts, services/apps/assignments/src/comment/comment.schema.ts, services/apps/assignments/src/comment/comment.service.ts, services/apps/assignments/src/course/course.service.ts, services/apps/assignments/src/embedding/embedding.controller.ts, services/apps/assignments/src/embedding/embedding.handler.ts, services/apps/assignments/src/embedding/embedding.service.ts, services/apps/assignments/src/evaluation/evaluation.controller.ts, services/apps/assignments/src/evaluation/evaluation.handler.ts, services/apps/assignments/src/evaluation/evaluation.service.ts, services/apps/assignments/src/moss/moss.controller.ts, services/apps/assignments/src/search/search.handler.ts, services/apps/assignments/src/solution/solution-auth.guard.ts, services/apps/assignments/src/solution/solution.controller.ts, services/apps/assignments/src/solution/solution.handler.ts, services/apps/assignments/src/solution/solution.schema.ts, services/apps/assignments/src/solution/solution.service.ts, services/apps/assignments/src/statistics/statistics.controller.ts, services/apps/assignments/src/statistics/statistics.service.ts
* Changed remaining `assignment` and `solution` references to ObjectId.
* Improved some aggregation pipelines.
* Used `MongooseRepository` and `EventRepository` everywhere to reduce boilerplate.
=> General Assignments Service Refactor

frontend/src/app/assignment/model/assignment.ts, frontend/src/app/assignment/model/solution.ts, frontend/src/app/assignment/modules/edit-assignment/code-search/code-search.component.html, frontend/src/app/assignment/modules/import/import-embeddings/import-embeddings.component.html, frontend/src/app/assignment/modules/import/import-embeddings/import-embeddings.component.ts, services/apps/assignments/src/assignment/assignment.schema.ts, services/apps/assignments/src/embedding/embedding.controller.ts, services/apps/assignments/src/embedding/embedding.dto.ts, services/apps/assignments/src/embedding/embedding.service.spec.ts, services/apps/assignments/src/embedding/embedding.service.ts, services/apps/assignments/src/embedding/openai.service.ts, services/package.json, services/pnpm-lock.yaml, services/tsconfig.json, services/types/ignore-file.d.ts
+ Added a way to ignore files and functions from embedding import using a .gitignore-like syntax.
=> Embedding Ignore Filters

frontend/src/app/assignment/model/config.ts, frontend/src/app/assignment/modules/assignment/search/search.component.html, frontend/src/app/assignment/modules/assignment/submit.service.ts, frontend/src/app/assignment/modules/shared/assignment-actions/assignment-actions.component.html, frontend/src/app/assignment/modules/shared/assignment-actions/assignment-actions.component.ts, frontend/src/app/assignment/modules/shared/pipes/clone-link.pipe.ts, frontend/src/app/assignment/modules/shared/pipes/fulibfeedback-link.pipe.ts, frontend/src/app/assignment/modules/shared/pipes/navigate-link.pipe.ts, frontend/src/app/assignment/modules/shared/shared.module.ts, frontend/src/app/assignment/modules/shared/snippet/snippet.component.html, frontend/src/app/assignment/modules/shared/snippet/snippet.component.ts, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.html, frontend/src/app/assignment/modules/solution/evaluation-modal/evaluation-modal.component.ts, frontend/src/app/assignment/modules/solution/share/share.component.html, frontend/src/app/assignment/modules/solution/share/share.component.ts, frontend/src/app/assignment/modules/solution/similar-modal/similar-modal.component.html, frontend/src/app/assignment/modules/solution/similar-modal/similar-modal.component.ts, frontend/src/app/assignment/modules/solution/snippet-list/snippet-list.component.html, frontend/src/app/assignment/modules/solution/snippet-list/snippet-list.component.ts
+ Added support for IntelliJ IDEA, PyCharm and WebStorm as possible IDEs. [fulibFeedback#3](https://github.com/fujaba/fulibFeedback/issues/3)
Note that the [IntelliJ Plugin](https://plugins.jetbrains.com/plugin/23254-fulibfeedback) is not yet publicly available as of 2023-01-01.
=> IntelliJ Plugin Support

frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.ts, services/apps/assignments/src/embedding/embedding.service.spec.ts, services/apps/assignments/src/solution/solution.controller.ts
* Searching for solutions using an invalid regex now displays an error message below the search bar.
=> Handle Invalid RegEx in Solution Search

frontend/src/app/assignment/services/assignment.service.ts, services/apps/assignments/src/assignment/assignment.controller.ts, services/apps/assignments/src/assignment/assignment.service.ts
* Assignment tasks are no longer visible to unauthorized users before the deadline is over.
* My Assignments no longer shows all assignments in the database if the user is not logged in and has no stored tokens.
=> Assignment Privacy

frontend/src/app/assignment/modules/assignment/statistics.service.ts, frontend/src/app/assignment/modules/assignment/statistics/statistics.component.html, services/apps/assignments/src/statistics/statistics.dto.ts, services/apps/assignments/src/statistics/statistics.module.ts, services/apps/assignments/src/statistics/statistics.service.ts
+ Statistics now show the average and total time for grading solutions as tracked by the assignees.
=> Assignee duration statistics

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/app/assignment/model/assignee.ts, frontend/src/app/assignment/modules/course/create-course/create-course.component.html, frontend/src/app/assignment/modules/edit-assignment/info/info.component.html, frontend/src/app/assignment/modules/solution/comment-list/comment-list.component.html, frontend/src/app/assignment/modules/solution/evaluation-form/evaluation-form.component.html, frontend/src/app/assignment/modules/solution/solution.module.ts, frontend/src/app/assignment/modules/solution/tasks/tasks.component.html, frontend/src/app/assignment/modules/solution/tasks/tasks.component.ts, frontend/src/app/services/markdown.service.ts, frontend/src/app/shared/markdown-editor/markdown-editor.component.html, frontend/src/app/shared/markdown-editor/markdown-editor.component.spec.ts, frontend/src/app/shared/markdown-editor/markdown-editor.component.ts, frontend/src/app/shared/shared.module.ts, services/apps/assignments/src/assignee/assignee.schema.ts
+ Added a way for assignees to track general notes that are invisible to the student.
+ Added a simple markdown editor for various supported fields.
=> Assignee Notes

.github/workflows/test-frontend.yml, .github/workflows/test-services.yml, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.html, frontend/src/app/assignment/modules/assignment/solution-table/solution-table.component.scss, frontend/src/app/assignment/modules/edit-assignment/code-search/code-search.component.html, frontend/src/app/assignment/modules/import/import-consent/import-consent.component.ts, frontend/src/app/assignment/modules/import/import-embeddings/import-embeddings.component.ts, frontend/src/app/assignment/modules/import/import-files/import-files.component.ts, frontend/src/app/assignment/modules/import/import-github/import-github.component.ts, frontend/src/app/assignment/modules/import/import-modal/import-modal.component.ts, frontend/src/app/assignment/modules/import/import-moss/import-moss.component.ts, frontend/src/app/assignment/modules/import/import-tab.interface.ts, services/apps/assignments/src/assignment/assignment.controller.ts, services/apps/assignments/src/embedding/embedding.service.ts
* OpenAI and Moss settings are properly saved again (introduced in #430)
* When loading the list of students during GitHub Import fails, a toast now informs about the problem (e.g. invalid token).
* Improved success messages for Import actions.
* When no assignees exist in an assignment, menus in the solution table now properly react.
* Editing the OpenAI model option now works correctly.
* Fixed z-fighting in solution table.
* Fixed some internal issues related to embedding imports.
=> Assignments Fixes

frontend/src/app/assignment/modules/edit-assignment/task-markdown.service.spec.ts, frontend/src/app/assignment/modules/edit-assignment/task-markdown.service.ts
- Switching between task list and markdown editor now preserves all structure and information correctly. #441
Closes #441
=> Fix Task to Markdown Conversion

.github/workflows/deploy-backend.yml, .github/workflows/deploy-frontend.yml, frontend/Dockerfile, frontend/angular.json, frontend/package.json, frontend/src/app/services/changelog.service.ts, frontend/src/environments/environment.prod.ts, frontend/src/environments/environment.standalone.ts, frontend/src/environments/environment.ts
The frontend now builds with a compile-time constant for the build version.
This is used to display the version number in the GitHub navbar menu.
The backend no longer needs to be build every time now.
=> Build Frontend Version into Image
